config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: { registrations: "players/registrations" }

  root to: "home#index"

  devise_scope :player do
    resources :games, only: %i(create show)

    namespace :api, defaults: { format: "json" } do
      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        resources :players, only: %i(show) do
          get "me", on: :collection
        end

        resources :games, only: %i(show) do
          member do
            get "events"
            put "join"
            put "leave"
            put "start"
            put "program_robot"
          end
        end
      end
    end
  end

  require "sidekiq/web"
  mount Sidekiq::Web, at: "/sidekiq"
end

app/models/player.rb
class Player < ActiveRecord::Base
  devise(:database_authenticatable, :registerable)
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    NOT_FOUND_ERRORS = [
      ActiveRecord::RecordNotFound,
      Fountain::EventStore::StreamNotFoundError,
      Fountain::Repository::AggregateNotFoundError,
    ]

    respond_to :json
    before_action :restrict_access
    rescue_from *NOT_FOUND_ERRORS, with: :not_found
    rescue_from DomainError, with: :domain_error
    rescue_from InvalidCommandError, with: :invalid_command_error

    skip_before_filter :verify_authenticity_token

    private

    def restrict_access
      head :unauthorized unless current_player
    end

    def current_player
      access_token = params[:access_token]
      Player.where(access_token: access_token).first if access_token.present?
    end
    memoize :current_player

    def not_found
      head :not_found
    end

    def domain_error(error)
      errors = [
        {
          code: error.class.name.underscore,
          title: error.class.name.underscore.humanize
        }
      ]
      render json: { errors: errors }, status: 422
    end

    def invalid_command_error(error)
      errors = error.command.errors.map do |attribute, msg|
        {
          code: attribute,
          title: msg
        }
      end
      render json: { errors: errors }, status: 422
    end
  end
end

app/controllers/api/v1/games_controller.rb
module Api
  module V1
    class GamesController < Api::BaseController
      def events
        events = gateway.event_store.load_all(GameAggregate.name, params[:id])
        respond_with(events.map do |event|
          {
            payload_type: event.payload_type.name,
            payload: event.payload
          }
        end)
      end

      def join
        dispatch_command! JoinGameCommand.new(
          id: params[:id],
          player_id: current_player.id
        )

        head :accepted
      end

      def leave
        dispatch_command! LeaveGameCommand.new(
          id: params[:id],
          player_id: current_player.id
        )

        head :accepted
      end

      def start
        dispatch_command! StartGameCommand.new(
          id: params[:id],
          player_id: current_player.id
        )

        head :accepted
      end

      def program_robot
        command = ProgramRobotCommand.new(
          id: params[:id],
          player_id: current_player.id,
          instruction_cards: parse_instruction_cards
        )
        dispatch_command! command

        head :accepted
      end

      private

      def parse_instruction_cards
        params.require(:instruction_cards).map do |param|
          InstructionCard.new(
            param[:action],
            param[:amount].to_i, # TODO fix this silly to_i
            param[:priority].to_i
          )
        end
      end
    end
  end
end

app/controllers/api/v1/players_controller.rb
module Api
  module V1
    class PlayersController < Api::BaseController
      def show
        player = Player.find(params[:id])
        respond_with player.attributes.slice("id", "name")
      end

      def me
        respond_with current_player
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  extend Memoist

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def new_uuid
    SecureRandom.uuid
  end

  def dispatch_command(command)
    gateway.dispatch(command)
  end

  def dispatch_command!(command)
    gateway.dispatch!(command)
  end

  def gateway
    @gateway ||= GatewayBuilder.build
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_player!

  def create
    game_id = new_uuid
    dispatch_command!(CreateGameCommand.new(id: game_id, player_id: current_player.id))
    redirect_to action: :show, id: game_id
  end

  def show
    render :show, layout: "game"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/players/registrations_controller.rb
class Players::RegistrationsController < Devise::RegistrationsController
  def new
    self.resource = CreatePlayerCommand.new
  end

  def create
    self.resource = command = CreatePlayerCommand.new(
      sign_up_params.merge(id: new_uuid, access_token: SecureRandom.hex)
    )
    if dispatch_command(command)
      redirect_to root_path, notice: "Your account has been created successfully."
    else
      render "new"
    end
  end

  private

  def sign_up_params
    params.require(:player).permit(
      :name, :email, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.haml
:javascript
  $(function() {
    window.app = new RoboRacer.App(
      "#{current_player.id}",
      "#{current_player.access_token}",
      "#{params[:id]}"
     );
  });

app/views/home/index.html.haml
.mod-landing
  .hero
    %h1 Choose your robot and race your friends!
    = button_to "Play now!", games_path, class: "button play-now"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Robo Racer

    = stylesheet_link_tag "application", media: "all"

    = javascript_include_tag "es5-shim" if Rails.env.test?
    = javascript_include_tag "application"

    = csrf_meta_tags

  %body
    %header.mod-header
      .layout-wrap
        %div
          = link_to "Robo Racer", root_path, class: "logo"

        %nav
          %a Play now!

          - if current_player
            %span.player-name= current_player.name
            = link_to "Log out", destroy_player_session_path, method: :delete

          - else
            = link_to "Log in", new_player_session_path
            = link_to "Sign up", new_player_registration_path

    .mod-body
      .layout-wrap
        .content
          = flash[:notice] if flash[:notice]
          = yield

    %footer.mod-footer
      .layout-wrap
        .content
          :markdown
            Robo Racer © 2015.
            Built with love by [Zilverline](https://www.zilverline.com).

app/views/layouts/game.html.haml
!!!
%html
  %head
    %title Robo Racer

    = stylesheet_link_tag "application", media: "all"

    = javascript_include_tag "es5-shim" if Rails.env.test?
    = javascript_include_tag "application"

    = csrf_meta_tags

  %body
    = yield